### ISSUE TITLE
requires for some example datasets？

### ISSUE THREAD

**Issue by haoaowei** [JCBucio/MagnetoPy#1]
hello，very excellent codes， I am a PHD of  geophysics in University of Sicence and Technology of China. I am trying to deal with magnetic data.   I am not sure whether you can share some example datasets(such as stationsfile,base file and and final outputfile),my email: haoaowei@mail.ustc.edu.cn.
 Best regards

**Comment by JCBucio** [comment]
Hello! I'm glad you liked the script, I'm working on a version with an user interface for MagnetoPy and the current version might have errors when querying the IGRF API since they recently added an API key to perform queries. But even without API access it should perform diurnal variance corrections with your base station data.

Anyway, I am sending you some sample files from a study on a geological fault in Morelia Michoacán, México. The description of each column comes in the README file of the repo.

I'll write to you when I have the version with user interface for MagnetoPy so you can test it.

Greetings!
[cerritos_datos_estaciones.csv](https://github.com/JCBucio/MagnetoPy/files/10933363/cerritos_datos_estaciones.csv)
[cerritos_estaciones_base.csv](https://github.com/JCBucio/MagnetoPy/files/10933367/cerritos_estaciones_base.csv)
[cerritos_output.csv](https://github.com/JCBucio/MagnetoPy/files/10933465/cerritos_output.csv)
